/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "mesh.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(mesh_MeshMessage, mesh_MeshMessage, AUTO)



