#pragma once
#include <cstdint>
#include <cstring>
#include <esp_now.h>
#include "src/crypto/Crypto.h"
#include "src/error/Error.h"
#include "src/error/ErrorCore.h"

namespace lattice {
namespace mesh {
namespace crypto {

// Register an ESP-NOW peer WITHOUT link-layer encryption (spec §2, proto v3):
// payload confidentiality/integrity is end-to-end (E2ECrypto.h), and unencrypted
// slots raise the ESP-NOW peer cap from ~6 to 20. The shared PMK stays set.
inline void registerPeerWithEspNow(const uint8_t mac[6]) {
  if (esp_now_is_peer_exist(mac))
    return;
  esp_now_peer_info_t info = {};
  memcpy(info.peer_addr, mac, 6);
  info.channel = 0;
  info.encrypt = false;
  lattice::err::checkEsp(esp_now_add_peer(&info), lattice::utils::ErrorType::COMMUNICATION_FAIL,
                         "registerPeerWithEspNow: add_peer failed");
}

// Extract ONLY the key generation branch from Mesh::loadOrGenerateKeypair().
// The load-from-EEPROM branch and EEPROM save remain in loadOrGenerateKeypair().
//
// Phase J: keygen via lattice::crypto::x25519_keygen (mbedtls, public
// curve-aware API — see src/crypto/Crypto.h for the byte-order model). Keys
// come back in the established big-endian storage/wire convention, already
// clamped, so on-device keys generated by any prior firmware generation —
// and this device's own future reloads of what it just generated — keep
// interpreting the same bytes the same way.
// err::fatal digit 3 (digits 1-2 belonged to the old entropy-seed and
// group-load sub-steps, now internal to the wrapper — retired).
inline void generateKeypair(uint8_t* priv32Out, uint8_t* pub32Out) {
  if (!lattice::crypto::x25519_keygen(priv32Out, pub32Out)) {
    lattice::err::fatal(lattice::core::ErrorTypeDigit::CONFIG, lattice::core::ModuleDigit::MESH, 3,
                        "MESH: keypair gen failed");
  }
}

} // namespace crypto
} // namespace mesh
} // namespace lattice
