#pragma once
#include <cstdint>
#include <cstring>
#include "src/crypto/Crypto.h"
#include "src/error/Error.h"
#include "src/error/ErrorCore.h"

namespace lattice {
namespace mesh {
namespace crypto {

// registerPeerWithEspNow moved to MeshTransport (Phase B Task 4, finding 19
// — it's peering, not crypto). See MeshTransport::registerPeerWithEspNow.

// Extract ONLY the key generation branch from Mesh::loadOrGenerateKeypair().
// The load-from-EEPROM branch and EEPROM save remain in loadOrGenerateKeypair().
//
// Phase J: keygen via lattice::crypto::x25519_keygen (mbedtls, public
// curve-aware API — see src/crypto/Crypto.h for the byte-order model). Keys
// come back in the established big-endian storage/wire convention, already
// clamped, so on-device keys generated by any prior firmware generation —
// and this device's own future reloads of what it just generated — keep
// interpreting the same bytes the same way.
// err::fatal digit 3 (digits 1-2 belonged to the old entropy-seed and
// group-load sub-steps, now internal to the wrapper — retired).
inline void generateKeypair(uint8_t* priv32Out, uint8_t* pub32Out) {
  if (!lattice::crypto::x25519_keygen(priv32Out, pub32Out)) {
    lattice::err::fatal(lattice::core::ErrorTypeDigit::CONFIG, lattice::core::ModuleDigit::MESH, 3,
                        "MESH: keypair gen failed");
  }
}

} // namespace crypto
} // namespace mesh
} // namespace lattice
