#!/usr/bin/env python3
"""Generate firmware/main/config/master_pubkey_pin.h from a masterkey.json
+ master MAC string. Idempotent — overwrites in place.

Usage: gen_master_pubkey_pin.py <masterkey.json> <aa:bb:cc:dd:ee:ff>
"""
import base64
import json
import re
import sys
from pathlib import Path
from typing import NoReturn

REPO_ROOT = Path(__file__).resolve().parent.parent
OUT = REPO_ROOT / "firmware/main/config/master_pubkey_pin.h"

def die(msg) -> NoReturn:
    print(f"gen_master_pubkey_pin: {msg}", file=sys.stderr)
    sys.exit(1)

def main(argv):
    if len(argv) != 3:
        die(f"usage: {argv[0]} <masterkey.json> <aa:bb:cc:dd:ee:ff>")
    keyfile = Path(argv[1])
    mac_str = argv[2]
    if not keyfile.is_file():
        die(f"masterkey.json not found: {keyfile}")
    data = json.loads(keyfile.read_text())
    pub_b64 = data.get("publicKey") or data.get("PublicKey")
    pub_array = data.get("public_key")
    if pub_b64:
        pub = base64.b64decode(pub_b64)
    elif pub_array is not None:
        pub = bytes(pub_array)
    else:
        die("publicKey/public_key field not found in masterkey.json")
    if len(pub) != 32:
        die(f"public key wrong length: {len(pub)}")
    mac_hex = re.sub(r"[^0-9a-fA-F]", "", mac_str)
    if len(mac_hex) != 12:
        die(f"MAC must be 6 bytes (12 hex chars): got {mac_str}")
    mac = bytes.fromhex(mac_hex)

    def as_c_array(b, per_line=8):
        rows = []
        for i in range(0, len(b), per_line):
            row = ", ".join(f"0x{byte:02X}" for byte in b[i:i+per_line])
            rows.append("    " + row + ",")
        return "\n".join(rows)

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        "#pragma once\n"
        "#include <cstdint>\n"
        "// Generated by tools/gen_master_pubkey_pin.py — do not edit by hand.\n"
        "namespace lattice { namespace mesh { namespace pin {\n"
        f"constexpr uint8_t MASTER_PUBKEY[32] = {{\n{as_c_array(pub)}\n}};\n"
        f"constexpr uint8_t MASTER_MAC[6] = {{ {', '.join(f'0x{b:02X}' for b in mac)} }};\n"
        "}}}\n"
    )
    print(f"wrote {OUT}")

if __name__ == "__main__":
    main(sys.argv)
